# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32

FROM docker.io/library/alpine:3.24.2@sha256:31b6477333eb8257db9e5d7c3a7264fd0467928756f0bbcc27d35bea5d28cdbd
ARG VERSION
ARG USER=nobody

RUN printf -- 'alias ll="ls -alh"\n' >>/etc/profile && \
    apk add --no-cache jq
USER ${USER}
